
export const lightTheme = {
    primary: '#006491',
    onPrimary: '#ffffff',
    primaryContainer: '#c9e6ff',
    onPrimaryContainer: '#001e2f',
    secondary: '#ab2a62',
    onSecondary: '#ffffff',
    secondaryContainer: '#ffd9e2',
    onSecondaryContainer: '#3e001d',
    tertiary: '#64597b',
    onTertiary: '#ffffff',
    tertiaryContainer: '#eaddff',
    onTertiaryContainer: '#201635',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
    background: '#fafcff',
    onBackground: '#001f2a',
    surface: '#fafcff',
    onSurface: '#001f2a',
    outline: '#72787e',
    surfaceVariant: '#dde3ea',
    onSurfaceVariant: '#41474d',
}

export const darkTheme = {
    primary: '#8aceff',
    onPrimary: '#00344e',
    primaryContainer: '#004b6f',
    onPrimaryContainer: '#c9e6ff',
    secondary: '#ffb1c8',
    onSecondary: '#650033',
    secondaryContainer: '#8b0b4a',
    onSecondaryContainer: '#ffd9e2',
    tertiary: '#cec0e8',
    onTertiary: '#352b4b',
    tertiaryContainer: '#4c4163',
    onTertiaryContainer: '#eaddff',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#001f2a',
    onBackground: '#bfe9ff',
    surface: '#001f2a',
    onSurface: '#bfe9ff',
    outline: '#8b9198',
    surfaceVariant: '#41474d',
    onSurfaceVariant: '#c1c7ce',
}